spring:
  datasource:
    url: jdbc:mysql://39.105.76.39:3306/test
    username: root
    password: root*1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.pengyj.springbootmybatis.domain
#  config-location: #
